### PR TITLE
Statscache packaging

### PR DESCRIPTION
**Pull request by rtnpro**
@ralphbean 

This branch contains changes required to be made to the repo for the purpose of packaging it.

Here's an initial SPEC file written: https://gist.github.com/rtnpro/20075dd4df631729d898
I am a bit confused about the files under `fedmsg.d/` dir? Is it only for development. As I see, the files in the `fedmsg` dir conflicts with the ones installed by `fedmsg` RPM package. Am I supposed to include only `fedmsg.d/statscache.py` in the package? What about logging conf? 
Or, shall I exclude them from the package totally and `ansible` scripts take care of them, as done in, https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/datagrepper/tasks/main.yml.
Please have a look and comment.

### CODE REVIEW

**Comment by ralphbean** [comment]
> Am I supposed to include only fedmsg.d/statscache.py in the package

Yes, just this file should do it.

We could also use `sed` in the `%prep` section to change the 'True' to 'False' in that file, so that it is not automatically enabled (or not.. your choice).

**Comment by ralphbean** [comment]
Note that, even though we'll ship a /etc/fedmsg.d/statscache.py as an example with the package, we will _still_ overwrite it with ansible so that we can point it at our actual postgres db, not a sqlite database.

**Comment by rtnpro** [comment]
@ralphbean what do I do about `logging.py`? I cannot put it in `/etc/fedmsg.d/`. We have logging for statscache in our local `fedmsg.d/logging.py`.

**Comment by ralphbean** [comment]
@rtnpro oh, it can just be ignored.  I'm fairly certain it is just a copy of the default /etc/fedmsg.d/logging.py.

There is some _statscache-specific_ logging configuration in `fedmsg.d/statscache.py`, though.

**Comment by rtnpro** [comment]
@ralphbean https://bugzilla.redhat.com/show_bug.cgi?id=1234605

**Comment by rtnpro** [comment]
@ralphbean Is it good to be merged?

**Comment by ralphbean** [comment]
Yup!  :+1: here.  Go for it.

**Pull request merged**
