### PR TITLE
Yield the json response only if the request was successfull

### PR DESCRIPTION
**Pull request by cverna**
Signed-off-by: Clement Verna <cverna@tutanota.com>

### CODE REVIEW

**Comment by pypingou** [comment]
Looks fine, what happens if the request doesn't return a 200?

**Comment by cverna** [comment]
response.json()['raw_messages'] does not exist so we have an exception 🤓

**Comment by pypingou** [comment]
That was before but now we check the returned code before trying to access the json data. So does the rest of the code can handle a return code of say 400?

**Comment by cverna** [comment]
This is executed in a for loop, so if we get a 400 the response will be ignored and we move to the next response

**Comment by pypingou** [comment]
Okido, 👍 for me :)

**Comment by cverna** [comment]
Thanks for the review

**Pull request merged**
